## MOVE THIS FILE to `.github/workflows/docker-build.yaml` TO EXECUTE IT

# This is a basic workflow to help you get started with Actions

name: Uda'CityShop [sha tag] - Package with Docker

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: docker_meta1
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/adservice
          # add git short SHA as Docker tag
          tag-sha: true
      -
        name: Docker meta
        id: docker_meta2
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/currencyservice
          # add git short SHA as Docker tag
          tag-sha: true
      -
        name: Docker meta
        id: docker_meta3
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend
          # add git short SHA as Docker tag
          tag-sha: true
      -
        name: Docker meta
        id: docker_meta4
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/productcatalogservice
          # add git short SHA as Docker tag
          tag-sha: true
      -
        name: Docker meta
        id: docker_meta5
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/adservice-v2
          # add git short SHA as Docker tag
          tag-sha: true

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: src/adservice
          file: src/adservice/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta1.outputs.tags }}
          labels: ${{ steps.docker_meta1.outputs.labels }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: src/currencyservice
          file: src/currencyservice/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta2.outputs.tags }}
          labels: ${{ steps.docker_meta2.outputs.labels }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: src/frontend
          file: src/frontend/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta3.outputs.tags }}
          labels: ${{ steps.docker_meta3.outputs.labels }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: src/productcatalogservice
          file: src/productcatalogservice/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta4.outputs.tags }}
          labels: ${{ steps.docker_meta4.outputs.labels }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: src/adservice-v2
          file: src/adservice-v2/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta1.outputs.tags }}
          labels: ${{ steps.docker_meta1.outputs.labels }}
